#!/usr/bin/env bash
#
# Visualize network bandwidth on a host
#
# # Created
# Author: Dave Eddy <ysap@daveeddy.com>
# Date: March 16, 2026
# License: MIT
#
# # Contributors
# - Dave Eddy <ysap@daveeddy.com>

declare -A DATA=()

if [[ -z $NO_COLOR ]]; then
	DIM=$'\e[2m'
	RST=$'\e[0m'
else
	DIM=
	RST=
fi

TITLE_FMT="$DIM%15s %15s %15s %15s$RST\\n"

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

format-bits() {
	local bits=$1
    local -n var=$2
    local -n color=$3

	if ((bits > 1000000)); then
		var="$((bits / 1000000)) mbps"
        color=$'\e[31m'
	elif ((bits > 1000)); then
		var="$((bits / 1000)) kbps"
        color=$'\e[33m'
	else
        #shellcheck disable=SC2034 # false positive due to nameref 
		var="$bits  bps"
        #shellcheck disable=SC2034 
        color=$'\e[32m'
	fi
}

process-iface() {
	local iface=$1
	local rx_bytes=$2
	local tx_bytes=$3

	# check if we've seen this interface before
	local old=${DATA[$iface]}

	# store the new data no matter what
	DATA[$iface]="$rx_bytes $tx_bytes"

	# stop here if we haven't seen this interface before
	if [[ -z $old ]]; then
		echo "> $iface old data not found"
		return 1
	fi

	local old_rx_bytes old_tx_bytes
	read -r old_rx_bytes old_tx_bytes <<< "$old"

	local d_rx_bytes=$((rx_bytes - old_rx_bytes))
	local d_tx_bytes=$((tx_bytes - old_tx_bytes))
	local d_total_bytes=$((d_rx_bytes + d_tx_bytes))

	local d_rx_bits=$((d_rx_bytes * 8))
	local d_tx_bits=$((d_tx_bytes * 8))
	local d_total_bits=$((d_total_bytes * 8))

    local rx tx total rx_color tx_color total_color
    format-bits "$d_rx_bits" rx rx_color
    format-bits "$d_tx_bits" tx tx_color
    format-bits "$d_total_bits" total total_color
    
     #shellcheck disable=SC2154 # shellcheck full choke on nameref
    printf -- "$%*s ${rx_color}%*s ${tx_color}%*s ${total_color}%*s\e[0m\n"\
              15 "$iface" 15 "$rx" 15 "$tx" 15 "$total"
}

deinit-term() {
	printf '\e[?1049l' # disable alternate buffer
	printf '\e[?25h' # show the cursor
}

init-term() {
	printf '\e[?1049h' # enable alternate buffer
	printf '\e[?25l' # hide the cursor
	printf '\e[H' # move the cursor home
}

main() {
	trap deinit-term EXIT
	init-term

	while true; do
		printf '\e[H' # move the cursor home

		# read /proc file
		local -a lines
		mapfile -t -s 2 lines < /proc/net/dev \
		    || fatal 'failed to read proc device'

		# loop each line in the file
		echo
		printf "$TITLE_FMT" interface receive transmit total

		local line
		for line in "${lines[@]}"; do
			local -a info
			read -ra info <<< "$line"
			local iface=${info[0]}
			local rx_bytes=${info[1]}
			local tx_bytes=${info[9]}

			local iface=${iface%:}

			process-iface "$iface" "$rx_bytes" "$tx_bytes"
		done
		echo

		sleep 1
	done
}

main "$@"

