#!/usr/bin/env bash
#
# Trim extraneous whitespace from the right of an input stream in a way that is
# aware of any ANSI styling.
#
# Basically, I don't like that `curl ysap.sh` has some extra whitespace to the
# right that causes it to word wrap on smaller terminals even though no visible
# characters are there - so I wrote this tool to clean it up.  This only works
# for lines that end in a reset sequence.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: August 14, 2025
# License: MIT

shopt -s extglob
RST=$'\e[0m'

while IFS= read -r line; do
	# note: this always reattaches a RST sequence so we might be adding one
	s=${line%"$RST"}
	s=${s%%+([ ])}
	s=$s$RST
	echo "$s"
done
