#!/usr/bin/env bash

git() {
	# run the command first
	command git "$@" || return

	# only check if we are succesful
	if [[ $1 == 'push' ]]; then
		echo
		echo "***********************************************"
		echo "> \"it's just going to ask you a question...\""
		echo "***********************************************"
		echo
		~/temp/leave-a-tip/tip
		read -s _
	fi

	return 0
}
