#!/usr/bin/env bash

regex='^.*\/(.*) - ([0-9]{4}-[0-9]{2}-[0-9]{2})\..*$'
for f in ./files/*; do
	if [[ $f =~ $regex ]]; then
		name=${BASH_REMATCH[1]}
		date=${BASH_REMATCH[2]}
		echo "$date: $name"
	fi
done
