#!/usr/bin/env bash

usage() {
	echo 'Usage: my-program [-h]'
}

u=false
while getopts 'hu' opt; do
	case "$opt" in
		h) usage; exit 0;;
		u) u=true;;
		*) usage >&2; exit 1;;
	esac
done
shift $((OPTIND - 1))

name=$1
if $u; then
	# -u was given, uppercase it!
	name=${name^^}
fi

echo "hello $name"
