#!/usr/bin/env bash

BATCHSIZE=1
BAR_CHAR='|'
EMPTY_CHAR=' '

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

progress-bar() {
	local current=$1
	local len=$2

	if [[ $len -eq 0 ]]; then
		exit
	fi
	local perc_done=$((current * 100 / len))

	local suffix=" $current/$len ($perc_done%)"

	local length=$((COLUMNS - ${#suffix} - 2))
	local num_bars=$((perc_done * length / 100))

	local i
	local s='['
	for ((i = 0; i < num_bars; i++)); do
		s+=$BAR_CHAR
	done
	for ((i = num_bars; i < length; i++)); do
		s+=$EMPTY_CHAR
	done
	s+=']'
	s+=$suffix

	printf '\e7' # save the cursor location
	  printf '\e[%d;%dH' "$LINES" 0 # move cursor to the bottom line
	  printf '\e[0K' # clear the line
	  printf '%s' "$s" # print the progress bar
	printf '\e8' # restore the cursor location
}

process-files() {
	local files=("$@")

	echo "processing batch of ${#files[@]} files"

	local file
	for file in "${files[@]}"; do
		echo "-> $file"
	done
	sleep .1
}

init-term() {
	printf '\n' # ensure we have space for the scrollbar
	  printf '\e7' # save the cursor location
	    printf '\e[%d;%dr' 0 "$((LINES - 1))" # set the scrollable region (margin)
	  printf '\e8' # restore the cursor location
	printf '\e[1A' # move cursor up
}

deinit-term() {
	printf '\e7' # save the cursor location
	  printf '\e[%d;%dr' 0 "$LINES" # reset the scrollable region (margin)
	  printf '\e[%d;%dH' "$LINES" 0 # move cursor to the bottom line
	  printf '\e[0K' # clear the line
	printf '\e8' # reset the cursor location
}

main() {
	local OPTARG OPTIND opt
	while getopts 'b:c:e:' opt; do
		case "$opt" in
			b) BATCHSIZE=$OPTARG;;
			c) BAR_CHAR=$OPTARG;;
			e) EMPTY_CHAR=$OPTARG;;
			*) fatal 'bad option';;
		esac
	done

	shopt -s globstar nullglob checkwinsize
	# this line is to ensure LINES and COLUMNS are set
	(:)

	trap deinit-term exit
	trap init-term winch
	init-term

	echo 'finding files'
	local files=(./**/*cache)
	local len=${#files[@]}
	echo "found $len files"

	local i
	for ((i = 0; i < len; i += BATCHSIZE)); do
		progress-bar "$((i+1))" "$len"
		process-files "${files[@]:i:BATCHSIZE}"
	done
	progress-bar "$len" "$len"
}

main "$@"
