#!/usr/bin/env bash

blue=$(tput setaf 6)
dark=$(tput setaf 4)
bold=$(tput bold)
rst=$(tput sgr0)

clear
cat <<-EOF
$blue~$rst
$blue~
$blue~
$blue~
$blue~
$blue~$rst
$blue~$rst
$blue~$rst
$blue~$rst
$blue~$rst
$blue~$rst
$blue~$rst                               VIM - Vi IMproved
$blue~$rst
$blue~$rst                                version 9.1.500
$blue~$rst                            by Bram Moolenaar et al.
$blue~$rst                  Vim is open source and freely distributable
$blue~
$blue~$rst                         Help poor children in Uganda!
$blue~$rst                 type  :help iccf$dark<Enter>$rst       for information
$blue~
$blue~$rst                 type  :q$dark<Enter>$rst               to exit
$blue~$rst                 type  :help$dark<Enter>$rst  or  $dark<F1>$rst  for on-line help
$blue~$rst                 type  :help version9$dark<Enter>$rst   for version info
$blue~$rst                 visit  ${blue}ysap.sh${rst} to activate vim
$blue~
$blue~
$blue~
$blue~                 $bold+----------------------------------------------+$rst
$blue~                 $bold| $rst${bold}Sorry, Vim isn't available right now                    |$rst
$blue~                 $bold|                                                |$rst
$blue~                 $bold| $rst${bold}Go to settings to activate Vim. |$rst
$blue~                 $bold+----------------------------------------------+$rst
$blue~
$blue~
$blue~
$blue~
$blue~
$blue~
$blue~
$blue~
EOF
