#!/usr/bin/env bash
#
# colors to be used for this website
# can be sourced in by any script
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 03, 2024
# License: MIT

GRAY_COLOR='\x1b[38;5;8m'
RED_COLOR='\x1b[38;5;9m'
GREEN_COLOR='\x1b[38;5;10m'
YELLOW_COLOR='\x1b[38;5;11m'
BLUE_COLOR='\x1b[38;5;12m'
MAGENTA_COLOR='\x1b[38;5;13m'
DIM_COLOR='\x1b[2m'
BOLD_COLOR='\x1b[1m'
RST_COLOR='\x1b[0m'

TABLE_COLOR=$GRAY_COLOR
HEADER_COLOR=$BOLD_COLOR
TITLE_COLOR=$GREEN_COLOR
DESC_COLOR=$YELLOW_COLOR
LINK_COLOR=$BLUE_COLOR
CODE_COLOR=$RED_COLOR
NUM_COLOR=$GRAY_COLOR
