#!/usr/bin/env bash
#
# Convert the list of episodes into JSON format
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

. ./util || exit 1

typ=$1
[[ -n $typ ]] || exit 1

objects=()

callback() {
	local _num=$1
	local title=$2
	local desc=$3
	local link=$4
	local tt=$5
	local yt=$6
	local ig=$7

	# this is an "episode" object in the final json
	local json
	read -d '' -r json <<-"EOF"
	{
		"title": $title,
		"desc": $desc,
		"link": $link,
		"external": {
			"tiktok": $tiktok,
			"youtube": $youtube,
			"instagram": $instagram
		}
	}
	EOF

	local object
	object=$(jq -c --null-input \
		--arg title "$title" \
		--arg desc "$desc" \
		--arg link "$link" \
		--arg tiktok "$tt" \
		--arg youtube "$yt" \
		--arg instagram "$ig" \
		"$json"
	) || exit
	objects+=("$object")
}
foreach-video "$typ" callback

now=$(date +%s)
printf '%s\n' "${objects[@]}" | jq -n \
    --arg site "https://$SITE" \
    --arg typ "$typ" \
    --argjson date "$now" \
    '{
    "name": "You Suck at Programming",
    "site": $site,
    "generated": $date,
    "type": $typ,
    "episodes": [inputs]
}'
