#!/usr/bin/env bash
#
# Take a list of text episodes and generate redirect pages
#
# This allows us to basically have our own URL shortener, albeit in HTML
# redirects and not HTTP - but still, it makes for smaller URLs.
#
# This will create files like:
#
# /v/4/index.html
#
# Which allows a user to request `GET /v/4` and get redirected to the tiktok
# video URL for episode 4.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

dir=$1

[[ -n $dir ]] || exit 1

NUM_RE='^[0-9]+'

# read episode info from stdin (parse txt file)
index=0
episodes=()
links=()
titles=()
descs=()
while read -r line; do
	case "$index" in
		0) # title
			num=${line%%.*}
			episodes+=("$num")
			titles+=("$line")
			;;
		1) # desc
			descs+=("$line")
			;;
		2) # link
			links+=("$line")
			;;
		3) ;;
	esac
	index=$(( (index + 1) % 4 ))
done
num_episodes=${#episodes[@]}

mkdir -p "$dir/v"
for ((i = 0; i < num_episodes; i++)); do
	episode=${episodes[i]}
	link=${links[i]}
	title=${titles[i]}
	desc=${descs[i]}

	echo "generating page for episode $episode -> $link"

	# sanity check - ensure the number is just a number
	[[ $episode =~ $NUM_RE ]] || exit 1

	mkdir -p "$dir/v/$episode"
	cat <<-EOF > "$dir/v/$episode/index.html"
<!doctype html>
<html>
	<head>
		<title>$title</title>
		<link rel="stylesheet" href="/style.css">
	</head>
	<body>
		<div id="container">
			<br>
			<a href="/">&larr; You suck at programming</a>
			<span class="center">
				<h1>$title</h1>
				<blockquote class="tiktok-embed" cite="$link" data-video-id="${link##*/}" data-embed-from="embed_page" style="width:325px;">
					<section>
						<a target="_blank" title="@bahamas10_" href="https://www.tiktok.com/@bahamas10_?refer=embed">@bahamas10_</a>
						<p>$desc</p>
						<a target="_blank" title="♬ original sound - Dave Eddy" href="https://www.tiktok.com/music/original-sound-7347734206501456683?refer=embed">♬ original sound - Dave Eddy</a>
					</section>
				</blockquote>
				<script async src="https://www.tiktok.com/embed.js"></script>
				<p>$desc</p>
				<br>
				<p><a href="$link">$link</a></p>
			</span>
		</div>
	</body>
</html>
	EOF
done
