#!/usr/bin/env bash
#
# Convert the list of episodes into JSON format
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

. ./util || exit 1

objects=()

callback() {
	local _num=$1
	local title=$2
	local desc=$3
	local link=$4
	local tt=$5
	local yt=$6
	local ig=$7

	local object
	object=$(jq -c --null-input \
		--arg title "$title" \
		--arg desc "$desc" \
		--arg link "$link" \
		--arg _tiktok_link "$tt" \
		--arg _youtube_link "$yt" \
		--arg _instagram_link "$ig" \
		'$ARGS.named') || exit
	objects+=("$object")
}
foreach-episode callback

now=$(date +%s)
printf '%s\n' "${objects[@]}" | jq -n --arg site "https://$SITE" --argjson date "$now" '{
    "name": "You Suck at Programming",
    "site": $site,
    "generated": $date,
    "episodes": [inputs]
}'
