#!/usr/bin/env bash
#
# Print the colorized YSAP logo and metadata
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

. ./colors || exit 1
. ./util || exit 1

mapfile -t logo < logo.txt

description=(
	""
	"${RST_COLOR}You Suck at Programming"
	"${RST_COLOR}Episodes and guide by dave eddy"
	"${BLUE_COLOR}https://$SITE${RST_COLOR} | ${BLUE_COLOR}https://daveeddy.com${RST_COLOR}"
	''
	"${RST_COLOR}Source: ${BLUE_COLOR}https://github.com/bahamas10/ysap${RST_COLOR}"
)

len=${#logo[@]}

for ((i = 0; i < len; i++)); do
	logo_line=${logo[i]}
	desc_line=${description[i]}

	echo -e "${BOLD_COLOR}$logo_line${RST_COLOR} $desc_line"
done
