#!/usr/bin/env bash
#
# Generate a help page with color
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

. ./colors || exit 1
. ./util || exit 1

echo -e "${GRAY_COLOR}# buy me a coffee${RST_COLOR}"
echo -e "> ${BLUE_COLOR}https://$SITE/ko-fi${RST_COLOR}"
