#!/usr/bin/env bash
#
# Make a page for each video by copying the static video page
#
# Can we use symlinks instead? for now just copy them because they are small
# files.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

num_re='^[0-9]+$'

echo 'making video pages in _site/v/...'

i=0
while IFS=$'\t' read -r num _; do
	# sanity
	[[ $num =~ $num_re ]] || exit
	mkdir -p "_site/v/$num"
	cat static/video.html > "_site/v/$num/index.html"
	((i++))
done < <(./make-list)

echo "made pages for $i videos"
