#!/usr/bin/env bash
#
# Print the YSAP logo
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit

read -d '' LOGO << EOF
AA  AA  AAAA     AAA   AAAAA
CC  CC CC  BB  ACB BCA CC  CC
 BCCB   BBBBCA CCAAACC CCAACB
  CC   BCAAACB CC   CC CC    
DDDDDDDDDDDDDDDDDDDDDDDDDDDDD
EEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EOF

LOGO=$(echo "$LOGO" | sed 's/[A|B]\+/'$COLOR5'\0'$RST'/g;'\
's/C\+/'$COLOR6'\0'$RST'/g;'\
's/D\+/'$COLOR7'\0'$RST'/g;'\
's/E\+/'$COLOR8'\0'$RST'/g;'\
's/[A|D|E]/▄/g;'\
's/B/▀/g;'\
's/C/ /g')

# LOGO=${LOGO//A/${COLOR5}▄$RST}
# LOGO=${LOGO//B/${COLOR5}▀$RST}
# LOGO=${LOGO//C/${COLOR6} $RST}
# LOGO=${LOGO//D/${COLOR7}▄$RST}
# LOGO=${LOGO//E/${COLOR8}▄$RST}

echo "$LOGO"
