#!/usr/bin/env bash
#
# Generate the page as seen by `curl ysap.sh/help`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit

{

# create the header
./make-header -p 7 |
    ./tools/box -hp 4 -T plain

echo

# create the legend
./make-legend -f

} | ./tools/lpad '  ' | ./tools/rtrim-ansi-aware
