#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Yo what's up everyone my name's
Dave and you suck at programming.
Connect with my socials or use this
site to easily find my content!
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
