#!/usr/bin/env bash
#
# Generate a footer
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 03, 2024
# License: MIT

. colors || exit 1

printf "${TABLE_COLOR}last updated: %s${RST_COLOR}\n" "$(TZ=utc date)"
