#!/usr/bin/env bash
#
# My personal color theme for the website - loosely based on a dark solarized
# theme
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 28, 2025
# License: MIT

COLOR1=$'\x1b[38;5;87m'            # cyan
COLOR2=$'\x1b[38;5;211m'           # magenta
COLOR3=$'\x1b[38;5;120m'           # green
COLOR4=$'\x1b[38;5;241m'           # dim
COLOR5=$'\x1b[38;5;223m'           # off-white (text)
COLOR6=$'\x1b[48;5;223m'           # off-white (background)
COLOR7=$'\x1b[38;5;160;49m'        # red
COLOR8=$'\x1b[38;5;214;48;5;202m'  # yellow (text) orange (background)
RST=$'\x1b[0m'
