#!/usr/bin/env bash
#
# util functions for building the ysap website
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: July 11, 2024
# License: MIT

SITE='ysap.sh'

foreach-episode() {
	local callback=$1
	local line title num desc

	for pt in ../episodes/pt*/meta.txt; do
		local line= title= num= desc=
		local tiktok= youtube= instagram=
		local lines links
		unset lines links

		mapfile -t lines < "$pt"

		title=${lines[0]}
		num=${title%%.*}
		title=${title#*. }

		link="https://$SITE/v/$num"
		desc=${lines[1]}

		lines=("${lines[@]:2}")
		declare -A links
		for line in "${lines[@]}"; do
			read -r key value <<< "$line"
			links[$key]=$value
		done

		tiktok=${links[tiktok]}
		youtube=${links[youtube]}
		instagram=${links[instagram]}

		[[ -n $tiktok && -n $youtube && -n $instagram ]] || continue

		"$callback" "$num" "$title" "$desc" "$link" \
		    "$tiktok" "$youtube" "$instagram"
	done
}
