#!/usr/bin/env bash
#
# util functions for building the ysap website
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: July 11, 2024
# License: MIT

SITE='ysap.sh'

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

foreach-video() {
	local typ=$1
	local callback=$2
	local line title num desc pt
	local lines links

	local base_link="https://$SITE"

	for pt in ../"$typ"/pt*/meta.txt; do
		unset lines links

		mapfile -t lines < "$pt"

		title=${lines[0]}
		num=${title%%.*}
		title=${title#*. }

		case "$typ" in
			episodes) link=$base_link/v/$num;;
			general) link=$base_link/general/v/$num;;
			*) fatal "unknown type $typ";;
		esac

		desc=${lines[1]}

		lines=("${lines[@]:2}")
		declare -A links
		for line in "${lines[@]}"; do
			read -r key value <<< "$line"
			[[ -n $key && -n $value ]] || continue
			links[$key]=$value
		done

		tiktok=${links[tiktok]}
		youtube=${links[youtube]}
		instagram=${links[instagram]}

		[[ -n $tiktok && -n $youtube && -n $instagram ]] || continue

		"$callback" "$num" "$title" "$desc" "$link" \
		    "$tiktok" "$youtube" "$instagram"
	done
}
