#!/usr/bin/env bash
#
# awk-tuah - split on that string!
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: November 08, 2024
# License: MIT

banner=$(cat <<-"EOF"
                .__  .__  __
   ____________ |  | |__|/  |_    ____   ____
  /  ___/\____ \|  | |  \   __\  /  _ \ /    \
  \___ \ |  |_> >  |_|  ||  |   (  <_> )   |  \
 /____  >|   __/|____/__||__|    \____/|___|  /
      \/ |__|                               \/
  __  .__            __              __         .__              ._.
_/  |_|  |__ _____ _/  |_    _______/  |________|__| ____    ____| |
\   __\  |  \\__  \\   __\  /  ___/\   __\_  __ \  |/    \  / ___\ |
 |  | |   Y  \/ __ \|  |    \___ \  |  |  |  | \/  |   |  \/ /_/  >|
 |__| |___|  (____  /__|   /____  > |__|  |__|  |__|___|  /\___  /__
           \/     \/            \/                      \//_____/ \/
EOF
)

fake-error() {
	cat <<-EOF
	awk: syntax error at source line 1
	 context is
	        {print >>>  $} <<<
	awk: illegal statement at source line 1

EOF
}

fake-usage() {
	cat <<-"EOF"
	awk: unknown option --help ignored

	awk: try passing `--tuah`

	EOF
}

banner() {
	tput bold
	echo "$banner"
	tput sgr0
}

case "$1" in
	-F) fake-error;;
	--help) fake-usage;;
	--tuah) banner;;
esac
